---
- name: 1. Create git user
  become: true
  user:
    name: git
    system: yes
    create_home: no

- name: 2. Get gogs release
  become: true
  unarchive:
    src: https://github.com/gogs/gogs/releases/download/v0.12.3/gogs_0.12.3_linux_armv8.zip
    dest: /srv
    remote_src: true
    owner: git
    group: git

- name: 3a. Install MariaDB
  become: true
  apt:
    name: mariadb-server
    update_cache: yes

- name: 3b. Start and enable service
  service: name=mysql state=started enabled=yes

- name: 3c. Install pip
  become: true
  apt:
    name: python3-pip

- name: 3d. Install PyMySQL
  pip:
    name: PyMySQL

- name: 3e. Create git database user
  become: true
  mysql_user:
    name: gogs
    password: gogs
    priv: '*.*:ALL'
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: 'root'

- name: 3f. Create gogs database
  become: true
  mysql_db:
    name: gogs
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: 'root'

- name: 4. Copy gogs service file
  become: true
  copy:
    src: /srv/gogs/scripts/systemd/gogs.service
    dest: /etc/systemd/system/gogs.service
    remote_src: true

- name: 5a. Configure gogs service
  become: true
  lineinfile:
    path: /etc/systemd/system/gogs.service
    regexp: 'After=mariadb\.service.*'
    line: After=mysql.service

- name: 5b. Configure gogs service
  become: true
  lineinfile:
    path: /etc/systemd/system/gogs.service
    regexp: 'ExecStart.*'
    line: ExecStart=/srv/gogs/gogs web

- name: 5c. Configure gogs service
  become: true
  lineinfile:
    path: /etc/systemd/system/gogs.service
    regexp: 'WorkingDirectory.*'
    line: 'WorkingDirectory=/srv/gogs'

- name: 6. Enable and start service
  become: true
  service:
    name: gogs
    enabled: yes
    state: started
