---
  - name: Install ntp for time sync
    apt:
      name: unattended-upgrades
      state: present

  - name: Check that the upgrade conf file exists
    stat:
      path: /etc/apt/apt.conf.d/20auto-upgrades
    register: stat_result

  - name: Create the file, if it doesnt exist already
    file:
      path: /etc/apt/apt.conf.d/20auto-upgrades
      state: touch
    when: stat_result.stat.exists == False 

  - name: Check config in file
    lineinfile:
      path: /etc/apt/apt.conf.d/20auto-upgrades
      line: 'APT::Periodic::Update-Package-Lists "1";'

  - name: Check config in file
    lineinfile:
      path: /etc/apt/apt.conf.d/20auto-upgrades
      line: 'APT::Periodic::Unattended-Upgrade "1";'
