---
  - name: Download install script
    get_url:
      url: https://deb.nodesource.com/setup_8.x
      dest: /tmp/setup_8.x
      mode: u+rwx

  - name: Execute install script
    become: true
    shell: /tmp/setup_8.x

  - name: Install nodejs
    become: true
    apt:
      name: nodejs
      state: present
