- name: Install fail2ban
  apt:
    name: fail2ban
    update_cache: yes
    state: present
  sudo: yes

- name: Copy fail2ban jail config
  copy: src=jail.local dest=/etc/fail2ban/jail_test.local owner=root group=root mode=0644
  sudo: yes

- name: Copy fail2ban ssh filter config
  copy: src=filter.d/sshd.conf dest=/etc/fail2ban/filter.d/sshd_test.conf owner=root group=root mode=0644
  sudo: yes

- name: (Re-)start rsyslog
  service: name=rsyslog state=restarted

- name: (Re-)start fail2ban
  service: name=fail2ban state=restarted
