---
  - name: Install apache
    apt:
      name: apache2
      update_cache: yes
      state: latest

  - name: Enable mod-proxy
    apache2_module: name=proxy state=present

  - name: Enable mod-proxy-http
    apache2_module: name=proxy_http state=present
    notify: retstart apache2
